import js from "@eslint/js";

// Minimal, modern-ESM ruleset (Phase 9 of docs/refactoring-plan.md):
// `@eslint/js` recommended rules only. No stylistic rules here - formatting
// is Prettier's job (see `npx prettier --check`), not ESLint's.
//
// `transpiled/` is jco's generated JS output (regenerated by `task build`,
// gitignored) and must never be linted as hand-written source.
export default [
  {
    ignores: ["node_modules/**", "transpiled/**"],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
  },
];
