#!/usr/bin/env bash
# Canonical lifecycle implementation for rust/component/.
#
# State ownership (Phase 7 of docs/refactoring-plan.md): HARNESS_DIR and its
# derived cache/output/CARGO_TARGET_DIR variables are defined once at the
# language root (rust/lifecycle.sh) and inherited here when this script runs
# as that script's delegate. For direct invocation (`cd rust/component &&
# task test`), this is the one shared fallback rule used by every child
# lifecycle.sh in this repo: derive HARNESS_DIR relative to the parent
# (language root) directory, then apply the identical derivation chain.
set -eu

script_dir="$(cd "$(dirname "$0")" && pwd)"

export HARNESS_DIR="${HARNESS_DIR:-$(cd "$script_dir/.." && pwd)/.harness}"
export HARNESS_CACHE_DIR="${HARNESS_CACHE_DIR:-$HARNESS_DIR/cache}"
export HARNESS_OUTPUT_DIR="${HARNESS_OUTPUT_DIR:-$HARNESS_DIR/outputs}"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$HARNESS_CACHE_DIR/cargo-target}"

cmd_setup() {
  cargo fetch --locked
}

# The one shared release-component build sequence, used by both cmd_build
# and cmd_coverage: compile every workspace member (one cargo-component
# package per WIT world: task-component and new-world-parser), leave the
# regenerated bindings rustfmt-clean, and copy both artifacts into place.
build_component_artifact() {
  cargo component build --release --locked --offline --workspace
  # cargo-component (re)generates each member's src/bindings.rs during the
  # build with formatting rustfmt rejects (Phase 0 baseline / Phase 9 of
  # docs/refactoring-plan.md: an over-long `link_section` attribute line).
  # The files are gitignored and deleted by `clean`, so formatting the
  # committed tree can never fix them - the build step itself must leave the
  # regenerated files rustfmt-clean for `cargo fmt --all --check` (the
  # `lint` verb) to pass from a fresh build. `--edition 2021` matches both
  # crates' Cargo.toml.
  rustfmt --edition 2021 src/bindings.rs new-world-parser/src/bindings.rs
  cp "$CARGO_TARGET_DIR/wasm32-wasip1/release/task_component.wasm" task-component.wasm
  cp "$CARGO_TARGET_DIR/wasm32-wasip1/release/new_world_parser.wasm" new-world-parser.wasm
}

cmd_build() {
  build_component_artifact
}

# build is a native dependency of test in both runners, so this only performs
# the leaf-level test invocation.
cmd_test() {
  cargo test --locked --offline --tests --workspace
}

# Formatter + lint gate (Phase 9 of docs/refactoring-plan.md). build is a
# native dependency of lint in both runners: `cargo fmt`/`cargo clippy` need
# each member's generated src/bindings.rs to exist (both lib.rs declare
# `mod bindings`), and the build step above is also what formats them. Both
# tools come from the Nix rust toolchain (rust/flake.nix minimal profile +
# clippy/rustfmt extensions), not a Cargo dependency. `--all`/`--workspace`
# cover every workspace member, not just the root package.
cmd_lint() {
  cargo fmt --all --check
  cargo clippy --all-targets --locked --offline --workspace -- -D warnings
}

# Explicitly upgrades locked dependencies and regenerates the lockfile
# (constitution.md §4). Network access is expected here, unlike the
# --locked --offline verbs above.
cmd_update() {
  cargo update
}

# coverage rebuilds its own instrumented artifact rather than depending on
# the plain `build` verb, matching current (pre-Phase-6) behavior. This
# still runs a full `cargo clean` before rebuilding (unrelated to the
# lifecycle `clean` verb below) to guarantee an untainted instrumented
# build; since CARGO_TARGET_DIR is shared with rust/library, this also
# clears that crate's cache - an accepted tradeoff of sharing one build
# cache (see rust/library/lifecycle.sh).
cmd_coverage() {
  cargo clean
  build_component_artifact
  cargo llvm-cov clean --workspace
  cargo llvm-cov --locked --offline --tests --workspace --fail-under-lines 100 --fail-under-functions 100 --fail-under-regions 100
}

# clean removes the copied output artifacts and each member's
# wit-bindgen-generated src/bindings.rs (analogous to Python's bindings/ and
# JavaScript's transpiled/ - build outputs, regenerated by the next
# `build`). The cargo build cache under $CARGO_TARGET_DIR is preserved
# (constitution.md §4: clean removes outputs, not caches/installed
# dependencies) - it is only removed by `purge`.
cmd_clean() {
  rm -f task-component.wasm new-world-parser.wasm src/bindings.rs new-world-parser/src/bindings.rs
}

# See rust/library/lifecycle.sh: CARGO_TARGET_DIR defaults to a directory
# shared with rust/library, so `cargo clean` here also clears that crate's
# cache. Accepted: root/rust orchestration always purges both together.
cmd_purge() {
  cargo clean
  rm -rf .task
}

verb="${1:-}"
case "$verb" in
  setup) cmd_setup ;;
  build) cmd_build ;;
  test) cmd_test ;;
  lint) cmd_lint ;;
  coverage) cmd_coverage ;;
  clean) cmd_clean ;;
  purge) cmd_purge ;;
  update) cmd_update ;;
  *)
    echo "lifecycle.sh: unknown verb '$verb'" >&2
    exit 64
    ;;
esac
